### ISSUE TITLE
Uploading Images Gives Error

### ISSUE THREAD

**Issue by d42ohpaz** [mlemgroup/mlem#1465]
**Describe the bug**
Uploading an image causes an error toast, and the uploaded image is not available in the comment. 

**Expected Behavior**
Image uploads, the markdown for the image be inserted into the comment where the cursor is at, and the bar above the keyboard (the shortcut bar) goes back to being shortcuts for markdown. 

**Actual Behavior**
An error toast is briefly displayed, and the shortcut bar continues to say Uploading and showing the progress spinner. To get the shortcut bar back, I have to cancel the comment and create a new one. 

**To Reproduce**
Open the new comment sheet, tap the image icon in the shortcut bar, select Photo Library, choose photo.  

**Mlem Information:**
2.0 (154)

**Additional Context**
I attempted to copy the photo from the Photos app, and use the Paste feature, but the app crashed. I sent a crash log at 8:14pm EDT from my Gmail that starts with _dohpaz_. 

I also cleared the cache, and I tried disabling auto-bypassing the image proxy.

**Comment by Sjmarf** [comment]
Thanks, I've fixed "Uploading..." getting stuck in #1467. 

The image you were uploading was probably too large. I've changed the toast to say "Image too large" rather than "error" in this case, to make it more clear.  If the error isn't because the image is too large, let me know and I'll look into it (you can tap on any "Error" toast to see what caused it btw).
