### ISSUE TITLE
Maybe add some space under the communities drop down for readability

### ISSUE THREAD

**Issue by capybeby** [mlemgroup/mlem#185]
## Introduction
If the communities drop down menu is opened over text it is kinda ugly and hard to look at.

## Requirements
Maybe add some space or a line to keep the two units separate. 

![IMG_1574](https://github.com/mlemgroup/mlem/assets/137654063/a7c05531-38e7-4477-ae37-afd9891588b2)

**Comment by EricBAndrews** [comment]
Can we maybe scrap that communities thing altogether? It's confusing, ugly, and feels bad

**Comment by WestonHanners** [comment]
to scrap it we will need a replacement search... maybe a tab.

**Comment by catniptree** [comment]
> Can we maybe scrap that communities thing altogether? It's confusing, ugly, and feels bad

It’s cool for changing communities quickly, maybe you can change it to be fullscreen instead of just halfscreen?

It was more of a „hidden feature“ in Apollo and very cool to use if you were used to it.

You could also pull down a search bar to search within a community, like in the iOS system settings app.

**Comment by JakeShirley** [comment]
Closing as the search tab exists now.  For community specific search we should open a specific item.  I do think that's a very valuable tool.
