### ISSUE TITLE
Add long-press/3D Touch context menu for images

### ISSUE THREAD

**Issue by raptormama** [mlemgroup/mlem#244]
One of the most commonly-used features of Apollo and similar clients is/was to save images posted by other users.

When viewing an image, whether it is as part of a post or standalone (after tapping on the image in a list of posts or from within a single post), the user should be able to press and hold (or 3D Touch, on older devices) to see a context menu that allows the user to save the image to the camera roll (and other relevant share sheet options) or to share it (email it, print it, forward it, et cetera).

**Comment by einsteinx2** [comment]
If my suggestion should be a separate Github issue, please let me know, but it would be nice to be able to directly share images rather than the Lemmy post link when the image is opened via 3D Touch/long press. Especially for memes, often I want to share just the image to either a family iMessage group or work Slack, and currently I have to do the following dance:

- Share post
- Use Opener to open in Safari
- Long press image
- Save to Photos
- Share Photo
- Delete Photo

Presumably the share menu on the post itself should always share the post and not just the post image, so I figured this would be a good place for direct image sharing.

**Comment by einsteinx2** [comment]
Whoops, I'm an idiot who didn't finish reading the post I replied to... I see you also mention direct sharing. Anyway I'll leave my reply up for the extra explanation of the use case for direct image sharing...

**Comment by EricBAndrews** [comment]
Child issue of #31

**Comment by EricBAndrews** [comment]
Closed in #767
