### ISSUE TITLE
Inconsistent markdown rendering between feed and post screen

### ISSUE THREAD

**Issue by Rexios80** [mlemgroup/mlem#361]
**Describe the bug**
The markdown rendering is working differently on the feed and post screens

**Expected Behavior**
They markdown renders the same no matter what screen it is on

**Actual Behavior**
The markdown is rendering differently on different screens

**To Reproduce**
Look at a post with the issue

**Mlem Information:**
1.0.0 (274)

**Additional Context**
Post: https://beehaw.org/post/6747080
![IMG_1992](https://github.com/mlemgroup/mlem/assets/7896519/25cb014f-0e98-44d7-a402-a2fdadc6c40c)
![IMG_1993](https://github.com/mlemgroup/mlem/assets/7896519/99550a17-fefc-4a14-836d-fc9daacb380c)

**Comment by EricBAndrews** [comment]
Labeling this one as 1.2 and a child of #62 

Turns out this is a super thorny problem--Swift offers a lovely little method for truncating lines (necessary in the feed), but it does not play well *at all* with Markdown. 

Current theories on how best to handle this:
- Strip all Markdown from feed presentation
- Custom Markdown handler with some sort of truncation feature

**Comment by fer0n** [comment]
Would you say stripping away markdown is sufficient?

I'm assuming links should stay as text and maybe even still be tappable? Hashtags as well? Don't know if I'll manage to make a decent solution for this, but I might give it a go if you want to assign this to me @EricBAndrews

**Comment by EricBAndrews** [comment]
We should be able to handle this one properly once the new markdown parsing (#1038) is in place--flagging for 2.0

**Comment by Sjmarf** [comment]
This is sorta fixed in 2.0. It'll render all "normal" markdown the same way, though inline images and spoilers aren't rendered and certain elements appear slightly different. This is because the post content needs to be entirely text in the feed so that we can apply `.lineLimit` - we don't have this limitation in the expanded post.
