### ISSUE TITLE
EditorTracker changes published on background thread 

### ISSUE THREAD

**Issue by boscojwho** [mlemgroup/mlem#682]
**Describe the bug**
<img width="737" alt="Screenshot 2023-10-01 at 12 11 54 AM" src="https://github.com/mlemgroup/mlem/assets/2549615/913d459d-137b-4e20-93ae-e27a66692c4e">

**Expected Behavior**
UI update ran on background thread.,

**Actual Behavior**
Needs to be main actor.

**To Reproduce**
Using reply action on swipey view seems to cause it.

**Mlem Information:**
- latest dev build.

**Comment by EricBAndrews** [comment]
This is due to the reply being wrapped up in an `async` function to be passed in as a swipe action. We'll have to figure out how to properly handle that case--I believe the original architecture was for swipey actions to all be synchronous, and wrap async tasks in a `Task` to pass them in as swipeys

**Comment by boscojwho** [comment]
Yea, that seems to be the case:
- It happens with the other swipe actions like collapse comments as well.
