### ISSUE TITLE
Make the links more hittable

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#746]
Links in post bodies can be very hard to tap. They should be parsed and aggregated (probably at the bottom of the post) as nice big tappable elements. 

Would make #116 trivially easy.

**Comment by ahti** [comment]
I think it would be worth investigating whether it could be enough to simply make the hitboxes for the links larger, rather than taking up a load of extra space for a stack of links. I haven't tested beyond tapping at a few links a few times, but rn it feels to me like the hitbox is exactly the size of the link, while there should be enough space to make it maybe 1.5-2 times the height.

**Comment by EricBAndrews** [comment]
That's a good idea, but probably infeasible in the short term--Apple's markdown support is notoriously finicky, and I would be very surprised if it supports something like this without some major hacks. In the longer term we're looking at custom markdown handling. I've linked this comment in that enhancement issue.
