### ISSUE TITLE
[0.19] Utilize new `creatorIsModerator` field

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#760]
0.19 introduces the `creatorIsModerator` field to the `APIPostView`. This will let us display mod flairs in feed! `PostModel` should be updated to make use of this and posts in feed should appropriately flair mods.

**Comment by Sjmarf** [comment]
Had a brief look at this, and I think this would be far easier to do once we've more fully adopted a model system... implementing this system new basically means passing a `PostModel` _in addition to the_ `APIPost` that we currently pass, which is less than ideal. 

An alternative is to add an initialiser to `PostModel` that accepts an `APIPost` rather than an `APIPostView`, so that we can create a `PostModel` wherever we only have access to an `APIPost` and not an `APIPostView`. This system is used in both `UserModel` and `CommunityModel`. The issue with this is that we'd have to make many of `PostModel`'s properties optional, including the `creator` and `community` attributes, because `APIPost` doesn't supply that data. This raises the question of what our approach towards 'missing' data in Models should be moving forward - the optional-properties approach that we're using in `UserModel` and `CommunityModel` works, but it would feel weird having to null coalesce the `creator` attribute of `PostModel` whenever we access it. I'm not sure what the best solution for that is though, unfortunately.
