### ISSUE TITLE
Cannot load Plex community (c/plex) on lemmy.ml

### ISSUE THREAD

**Issue by BrooklynMan** [mlemgroup/mlem#80]
**Describe the bug**
Cannot load Plex community (c/plex) on lemmy.ml

**Expected Behavior**
load Plex community (c/plex) on lemmy.ml

**Actual Behavior**
Cannot load Plex community (c/plex) on lemmy.ml

**To Reproduce**
attempt to load Plex community (c/plex) on lemmy.ml
- via community list search
- via tilebar search from feed
- via link in text
- via link in comment/post body (posted from link)

**Mlem Information:**
0.1.0 + 19 (also in previous versions)

**Additional Context**
I've seen other users mention that there are a small number of other communities that happens with

**Comment by ShadowJonathan** [comment]
We shouldn't parse URLs, every instance might have its own way of displaying communities (there is already a discrepancy between lemmy and kbin), we should chuck it at ResolveObject and let the local lemmy instance find it.

This is probably a child issue of #85

**Comment by EricBAndrews** [comment]
Marking this as closed, /c/plex loads just fine in the current dev build

**Comment by Sjmarf** [comment]
> Marking this as closed, /c/plex loads just fine in the current dev build

That's because the problematic URL doesn't appear on the front page of c/pled at this time - the issue hasn't gone away, it just doesn't apply to this particular case anymore. Theoretically, a similarly faulty URL could appear in the main feed, which would be much more disruptive. We should still try to fix this issue.
