### ISSUE TITLE
Swipe actions aren't disabled for a comment in the reply composer sheet when the comment is from the inbox

### ISSUE THREAD

**Issue by Sjmarf** [mlemgroup/mlem#813]
<img src="https://github.com/mlemgroup/mlem/assets/78750526/f7234d5f-0b86-4c66-b729-8b7a97ac5b41" width=50%>

**Comment by boscojwho** [comment]
Ah, I see why this is happening:
- `InboxReplyView` unconditionally adds a swipey view, when it shouldn't when embeded in a reply.
- Need a way to tell `InboxReplyView` when it is embedded.
- The other editor views don't have this issue because we are embedded a child view, and the `addSwipeyView` modifies a parent view.
