### ISSUE TITLE
"Instance appears to be offline" error popping up over and over

### ISSUE THREAD

**Issue by jeikashu** [mlemgroup/mlem#846]
**Describe the bug**
Opened the app and I have the error popping up over and over for x seconds. But everything seems to be working as intended.

**Expected Behavior**
The error doesn't pop up.

**Actual Behavior**
See description above.

**To reproduce**
Open the app and it pops up straight away. My account is on lemmy.zip

**Mlem Information:**
1.1.2 (792)

**Comment by Sjmarf** [comment]
Hey! I can't reproduce this one at the moment. It would help me to track down this error if you could provide more information:

1) Does this happen every single time you open the app?
2) If you have more than one account, does this also happen on your other accounts? Or just lemmy.zip?
3) If the answer to question 1 is "yes", try clearing your recent searches in the "search" tab. Does the error still occur if you do that?

**Comment by jeikashu** [comment]
Yeah I can't reproduce it either now, so I guess it's fixed. 

But still, the notification is kinda annoying as it keeps disappearing and appearing constantly, when it actually does appear. 

Also, wouldn't it be a good idea to have logs somewhere? That would help troubleshooting such stuff. Unless I don't see the button in the app.

**Comment by Sjmarf** [comment]
> But still, the notification is kinda annoying as it keeps disappearing and appearing constantly, when it actually does appear.

Yeah, I agree. If a call is made to the API and the instance can't be reached, it'll send the notification. Because many calls are made to the API when the app opens, they stack up. I'll look into less annoying ways to handle this.

> Also, wouldn't it be a good idea to have logs somewhere? That would help troubleshooting such stuff. Unless I don't see the button in the app.

We don't have in-app logs at the moment, no. It's probably a good idea. In some places, you'll get an option to copy the full debug error message when an error occurs. This makes it easier for us to debug it if the user chooses to submit a bug report. We haven't expanded this to everywhere in the app yet, though.

**Comment by jeikashu** [comment]
Awesome! Thanks for all the work you're all doing :)

**Comment by EricBAndrews** [comment]
Closing as stale--better notification handling is planned for 2.0, and this bug appears to be server-side.
