### ISSUE TITLE
2.0: SearchView

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#939]
Good as-is, just needs update to new middleware models

**Comment by Sjmarf** [comment]
I think post searching (#87) is something we should do in 2.0, with the ability to filter by community/user. We [discussed this on Slack](https://mlemhq.slack.com/archives/C05J3BS4FQU/p1708187087980369) back in February, and talked about how removing the "Top Results" tab might be necessary. This is because post searching is significantly slower than community searching - it takes up to 5 seconds to search for a post, compared to the almost instantaneous community search. Because community search is probably the most frequently used category, removing the "Top Results" tab and instead setting the "Communities" tab as the default would be the best option in my opinion.
