### ISSUE TITLE
2.0: Rebuild basic app structure

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#940]
*Depends on API and middleware code to log in/onboard*

- Add onboarding/login flow
- Add infrastructure to determine current account
- Add infrastructure for guest mode

**Comment by Sjmarf** [comment]
When a user first opens the app, I think they should be prompted to choose an instance to visit as a guest, rather than create an account. 

When in guest mode, the profile tab could be renamed to "Instance" and show the `InstanceView` for the active instance. At the top of the page, we could have big full-width "Create Account" and "Switch Instance" buttons.

We might be able to look into in-app account creation for 2.0, too. It could be a little tricky, however, since I believe account creation still works via websocket rather than the REST API.

I think the Inbox tab should stay in Guest mode. We might be able to  use it to notify you when your account has been approved, if creating the account required an application.
